export interface CreateQuotationI { 
link: string, 
productName: string,
price: number, 
quantity: number, 
photography: string,
category: number, 
subcategory:number, 
weight: number, 
pound: number, 
tall: number,
width: number, 
long: number,
provider: number,
surcharge: number, 
delivery: number,
tax: number,
}